# Post code coverage summary as a Bitbucket Pull Request comment
# Requires BB_AUTH_STRING environment variable (username:api_token in base64)

param(
    [string]$CoverageFile = "test-results\coverage.cobertura.xml"
)

# Only run in PR context
if (-not $env:BITBUCKET_PR_ID) {
    Write-Host "Not a pull request - skipping coverage comment" -ForegroundColor Yellow
    exit 0
}

if (-not (Test-Path $CoverageFile)) {
    Write-Host "Coverage file not found: $CoverageFile" -ForegroundColor Yellow
    exit 0
}

if (-not $env:BB_AUTH_STRING) {
    Write-Host "BB_AUTH_STRING not set - skipping coverage comment" -ForegroundColor Yellow
    Write-Host "Set this as a secured repository variable: base64(username:api_token)" -ForegroundColor Gray
    exit 0
}

Write-Host "Parsing coverage data..." -ForegroundColor Cyan

try {
    [xml]$coverage = Get-Content $CoverageFile
    $lineRate = [math]::Round([double]$coverage.coverage.'line-rate' * 100, 2)
    $branchRate = [math]::Round([double]$coverage.coverage.'branch-rate' * 100, 2)
    $linesCovered = $coverage.coverage.'lines-covered'
    $linesValid = $coverage.coverage.'lines-valid'
    $branchesCovered = $coverage.coverage.'branches-covered'
    $branchesValid = $coverage.coverage.'branches-valid'
    
    # Build coverage comment
    $comment = @"
## 📊 Code Coverage Report

| Metric | Coverage | Details |
|--------|----------|---------|
| **Lines** | **${lineRate}%** | ${linesCovered}/${linesValid} lines covered |
| **Branches** | **${branchRate}%** | ${branchesCovered}/${branchesValid} branches covered |

Coverage files are available in pipeline artifacts.

---
*Generated by automated pipeline*
"@

    # Post comment to PR
    $workspace = $env:BITBUCKET_WORKSPACE
    $repo = $env:BITBUCKET_REPO_SLUG
    $prId = $env:BITBUCKET_PR_ID
    
    $apiUrl = "https://api.bitbucket.org/2.0/repositories/$workspace/$repo/pullrequests/$prId/comments"
    
    $body = @{
        content = @{
            raw = $comment
        }
    } | ConvertTo-Json -Depth 3
    
    $headers = @{
        "Authorization" = "Basic $env:BB_AUTH_STRING"
        "Content-Type" = "application/json"
    }
    
    Write-Host "Posting coverage comment to PR #$prId..." -ForegroundColor Green
    
    $response = Invoke-RestMethod -Uri $apiUrl -Method Post -Headers $headers -Body $body
    
    Write-Host "✓ Coverage comment posted successfully!" -ForegroundColor Green
    
} catch {
    Write-Host "Failed to post coverage comment: $_" -ForegroundColor Red
    Write-Host "Continuing pipeline..." -ForegroundColor Yellow
    # Don't fail the pipeline
    exit 0
}
