# Post code coverage and test summary as a GitHub Pull Request comment
# Requires GH_TOKEN environment variable (set automatically by GitHub Actions)
#
# Used by GitHub Actions CI pipeline.

param(
    [string]$CoverageFile = "test-results\coverage.cobertura.xml",
    [string]$JunitFile = "test-results\junit.xml"
)

# Only run in PR context
if ($env:GITHUB_EVENT_NAME -ne "pull_request") {
    Write-Host "Not a pull request - skipping coverage comment" -ForegroundColor Yellow
    exit 0
}

if (-not $env:GH_TOKEN) {
    Write-Host "GH_TOKEN not set - skipping coverage comment" -ForegroundColor Yellow
    exit 0
}

# Extract PR number from GITHUB_REF (refs/pull/<number>/merge)
$prNumber = $null
if ($env:GITHUB_REF -match 'refs/pull/(\d+)/merge') {
    $prNumber = $Matches[1]
}

if (-not $prNumber) {
    Write-Host "Could not determine PR number from GITHUB_REF: $env:GITHUB_REF" -ForegroundColor Yellow
    exit 0
}

Write-Host "Preparing coverage comment for PR #$prNumber..." -ForegroundColor Cyan

# Build the comment body
$commentParts = @()
$commentParts += "## Code Coverage Report"
$commentParts += ""

# Add coverage data if available
if (Test-Path $CoverageFile) {
    try {
        [xml]$coverage = Get-Content $CoverageFile
        $lineRate = [math]::Round([double]$coverage.coverage.'line-rate' * 100, 2)
        $branchRate = [math]::Round([double]$coverage.coverage.'branch-rate' * 100, 2)
        $linesCovered = $coverage.coverage.'lines-covered'
        $linesValid = $coverage.coverage.'lines-valid'
        $branchesCovered = $coverage.coverage.'branches-covered'
        $branchesValid = $coverage.coverage.'branches-valid'

        $commentParts += "| Metric | Coverage | Details |"
        $commentParts += "|--------|----------|---------|"
        $commentParts += "| **Lines** | **${lineRate}%** | ${linesCovered}/${linesValid} lines covered |"
        $commentParts += "| **Branches** | **${branchRate}%** | ${branchesCovered}/${branchesValid} branches covered |"
        $commentParts += ""
    } catch {
        Write-Host "WARNING: Failed to parse coverage file: $_" -ForegroundColor Yellow
        $commentParts += "> Coverage data could not be parsed."
        $commentParts += ""
    }
} else {
    Write-Host "Coverage file not found: $CoverageFile" -ForegroundColor Yellow
    $commentParts += "> No coverage data available."
    $commentParts += ""
}

# Add test results if available
if (Test-Path $JunitFile) {
    try {
        [xml]$junit = Get-Content $JunitFile
        $totalTests = [int]$junit.testsuites.tests
        $failures = [int]$junit.testsuites.failures
        $errors = [int]$junit.testsuites.errors
        $skipped = [int]$junit.testsuites.skipped
        $passed = $totalTests - $failures - $errors - $skipped

        $commentParts += "### Test Results"
        $commentParts += ""
        $commentParts += "| Metric | Count |"
        $commentParts += "|--------|-------|"
        $commentParts += "| Total | $totalTests |"
        $commentParts += "| Passed | $passed |"
        if ($failures -gt 0) {
            $commentParts += "| Failed | $failures |"
        }
        if ($errors -gt 0) {
            $commentParts += "| Errors | $errors |"
        }
        if ($skipped -gt 0) {
            $commentParts += "| Skipped | $skipped |"
        }
        $commentParts += ""
    } catch {
        Write-Host "WARNING: Failed to parse JUnit file: $_" -ForegroundColor Yellow
    }
}

$commentParts += "---"
$commentParts += "*Generated by CI pipeline*"

$comment = $commentParts -join "`n"

try {
    Write-Host "Posting coverage comment to PR #$prNumber..." -ForegroundColor Green

    # Use gh CLI to post/update the PR comment
    $comment | gh pr comment $prNumber --body-file -

    Write-Host "Coverage comment posted successfully!" -ForegroundColor Green

} catch {
    Write-Host "Failed to post coverage comment: $_" -ForegroundColor Red
    Write-Host "Continuing pipeline..." -ForegroundColor Yellow
    # Don't fail the pipeline
    exit 0
}
